Name: Muley, Tushar

Title: Exercise_5-2_Week_5_Sample_Code

Date: April 18, 2021

In [1]:
#Import Libraries
import pandas as pd
import numpy as np
import json
import sys
import warnings
from sklearn.datasets import make_regression
from sklearn.feature_selection import RFECV
from sklearn import datasets, linear_model
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.decomposition import NMF
from sklearn import datasets
from sklearn.model_selection import train_test_split


In [2]:
#9.1 reducing features using Principal Components
digits = datasets.load_digits()
features= StandardScaler().fit_transform(digits.data)
pca=PCA(n_components=0.99, whiten=True)
features_pca = pca.fit_transform(features)
print("original number of features:", features.shape[1])
print("reduced number of features:", features_pca.shape[1])
print("output from 9.1 done!")

original number of features: 64
reduced number of features: 54
output from 9.1 done!


In [3]:
#9.4 Reducing Features Using Matrix Factorization
features = digits.data
nmf=NMF(n_components=10, random_state=1)
features_nmf=nmf.fit_transform(features)
print("Original number of features:", features.shape[1])
print("reduced number of features:", features_nmf.shape[1])
print("output from 9.4 done!")


Original number of features: 64
reduced number of features: 10
output from 9.4 done!


C:\Users\Tushar\anaconda3\lib\site-packages\sklearn\decomposition\_nmf.py:1076: ConvergenceWarning: Maximum number of iterations 200 reached. Increase it to improve convergence.
  warnings.warn("Maximum number of iterations %d reached. Increase it to"


In [4]:
#10.1 - Thresholding Numerical Feature Variance

from sklearn import datasets
from sklearn.feature_selection import VarianceThreshold



In [5]:
#import data
iris= datasets.load_iris()



In [6]:
#create features and target
features=iris.data
target=iris.target



In [7]:
#create thresholder
thresholder = VarianceThreshold(threshold=.5)



In [8]:
#create high variance feature matrix and print
features_high_variance=thresholder.fit_transform(features)
print(features_high_variance[0:3])



[[5.1 1.4 0.2]
 [4.9 1.4 0.2]
 [4.7 1.3 0.2]]


In [9]:
#10.2 - Thresholding Binary Feature Variance

features = [[0,1,0],
            [0,1,1],
            [0,1,0],
            [0,1,1],
            [1,0,0]]

thresholder=VarianceThreshold(threshold = (.75*(1-.75)))
print(thresholder.fit_transform(features))


[[0]
 [1]
 [0]
 [1]
 [0]]
